"use client";

import { Component as AppWindowIcon } from "lucide-static/icons/app-window.svg?svgUse";
import { Component as ArrowDownIcon } from "lucide-static/icons/arrow-down.svg?svgUse";
import { Component as ArrowRightIcon } from "lucide-static/icons/arrow-right.svg?svgUse";
import { Component as BinaryIcon } from "lucide-static/icons/binary.svg?svgUse";
import { Component as BlocksIcon } from "lucide-static/icons/blocks.svg?svgUse";
import { Component as BracesIcon } from "lucide-static/icons/braces.svg?svgUse";
import { Component as BracketsIcon } from "lucide-static/icons/brackets.svg?svgUse";
import { Component as Code2Icon } from "lucide-static/icons/code-2.svg?svgUse";
import { Component as CpuIcon } from "lucide-static/icons/cpu.svg?svgUse";
import { Component as DatabaseIcon } from "lucide-static/icons/database.svg?svgUse";
import { Component as ExternalLinkIcon } from "lucide-static/icons/external-link.svg?svgUse";
import { Component as FileCode2Icon } from "lucide-static/icons/file-code-2.svg?svgUse";
import { Component as FileCodeIcon } from "lucide-static/icons/file-code.svg?svgUse";
import { Component as GitBranchIcon } from "lucide-static/icons/git-branch.svg?svgUse";
import { Component as GithubIcon } from "lucide-static/icons/github.svg?svgUse";
import { Component as HardDriveIcon } from "lucide-static/icons/hard-drive.svg?svgUse";
import { Component as LayersIcon } from "lucide-static/icons/layers.svg?svgUse";
import { Component as LayoutIcon } from "lucide-static/icons/layout.svg?svgUse";
import { Component as LinkedinIcon } from "lucide-static/icons/linkedin.svg?svgUse";
import { Component as MailIcon } from "lucide-static/icons/mail.svg?svgUse";
import { Component as MenuIcon } from "lucide-static/icons/menu.svg?svgUse";
import { Component as MoonIcon } from "lucide-static/icons/moon.svg?svgUse";
import { Component as NetworkIcon } from "lucide-static/icons/network.svg?svgUse";
import { Component as PackageIcon } from "lucide-static/icons/package.svg?svgUse";
import { Component as PaletteIcon } from "lucide-static/icons/palette.svg?svgUse";
import { Component as SendIcon } from "lucide-static/icons/send.svg?svgUse";
import { Component as ServerCogIcon } from "lucide-static/icons/server-cog.svg?svgUse";
import { Component as ServerIcon } from "lucide-static/icons/server.svg?svgUse";
import { Component as SunIcon } from "lucide-static/icons/sun.svg?svgUse";
import { Component as TerminalSquareIcon } from "lucide-static/icons/terminal-square.svg?svgUse";
import { Component as TerminalIcon } from "lucide-static/icons/terminal.svg?svgUse";
import { Component as WindIcon } from "lucide-static/icons/wind.svg?svgUse";
import { Component as WorkflowIcon } from "lucide-static/icons/workflow.svg?svgUse";
import { Component as XIcon } from "lucide-static/icons/x.svg?svgUse";
import { Component as ZapIcon } from "lucide-static/icons/zap.svg?svgUse";

export const AppWindow = AppWindowIcon;
export const ArrowDown = ArrowDownIcon;
export const ArrowRight = ArrowRightIcon;
export const Binary = BinaryIcon;
export const Blocks = BlocksIcon;
export const Braces = BracesIcon;
export const Brackets = BracketsIcon;
export const Code2 = Code2Icon;
export const Cpu = CpuIcon;
export const Database = DatabaseIcon;
export const ExternalLink = ExternalLinkIcon;
export const FileCode2 = FileCode2Icon;
export const FileCode = FileCodeIcon;
export const GitBranch = GitBranchIcon;
export const Github = GithubIcon;
export const HardDrive = HardDriveIcon;
export const Layers = LayersIcon;
export const Layout = LayoutIcon;
export const Linkedin = LinkedinIcon;
export const Mail = MailIcon;
export const Menu = MenuIcon;
export const Moon = MoonIcon;
export const Network = NetworkIcon;
export const Package = PackageIcon;
export const Palette = PaletteIcon;
export const Send = SendIcon;
export const ServerCog = ServerCogIcon;
export const Server = ServerIcon;
export const Sun = SunIcon;
export const TerminalSquare = TerminalSquareIcon;
export const Terminal = TerminalIcon;
export const Wind = WindIcon;
export const Workflow = WorkflowIcon;
export const X = XIcon;
export const Zap = ZapIcon;
